# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: back-lint
        name: back lint
        entry: make back-lint
        require_serial: true
        language: system
        types: [python]

      - id: back-format
        name: back format
        entry: make back-format
        require_serial: true
        language: system
        types: [python]

      - id: back-typecheck
        name: back typecheck
        entry: make back-typecheck
        require_serial: true
        language: system
        types: [python]

      - id: front-lint
        name: front lint
        entry: make front-lint
        require_serial: true
        language: system
        types_or: [javascript, jsx, ts, tsx]

      - id: front-typecheck
        name: front typecheck
        entry: make front-typecheck
        require_serial: true
        language: system
        types_or: [ts, tsx]
        pass_filenames: false
